# For use with the Rest Client VSCode extension (humao.rest-client)

@baseUrl=https://wom22-projekt2-2.azurewebsites.net

GET {{baseUrl}}/services

### SKAFFA BD_BEAVER

POST {{baseUrl}}/services
Content-Type: application/json

{
    "cabin": "Test2",
    "servicetype": "bar",
    "price": 500
}


###

PATCH {{baseUrl}}/services
Content-Type: application/json

{
    "id": 1,
    "cabin": "Cabin id",
    "servicetype": "Chimney sweep",
    "price": 80
}

###

DELETE {{baseUrl}}/services
Content-Type: application/json

{
    "id": 2
}